import { AppConstant } from "./AppConstant";

// var total = 0;
export const MRKColumn = () => {
  return [
    { header: "Name", key: "name" },
    { header: "Age", key: "age" },
    { header: "Location", key: "location" },
  ];
};
export const MRKRows = () => {
  return [
    { time_to_draw: "John Doe" },
    { dr_time: "Jane Smith" },
    { dr_date: "Jane Smith" },
    { balance_cradit: "Jane Smith" },
    { last_tr_no: "Jane Smith" },
    { last_tr_pt: "Jane Smith" },
  ];
};
export const HistoryRows = [
  { userName: "User Name" },
  { DrDate: "Dr Date" },
  { DrTime: "Dr Time" },
  { game: "Game Type" },
  { startPoint: "Start Point" },
  { winPosition: "Win Position" },
  { bet: "Bet" },
];

export const BreadcumbsArray = [
  {icon:'fa-solid fa-chart-simple',url:AppConstant.MARKET_NEW,title:'Market'},
  {icon:'fa-solid fa-clock-rotate-left',url:AppConstant.HISTORY,title:'History',active:true},
]

export const listArray = [
  {
    number: "10",
    name: "Relience Industries",
    symbol: "RLSINDS",
    market: "NSE",
    className: "row_selected",
  },
  {
    number: "10",
    name: "Tata Motors",
    symbol: "TATANTRS",
    market: "BSE",
    className: "row_selected",
  },
  {
    number: "10",
    name: "Aditya B",
    symbol: "ADBRGRP",
    market: "BSE",
    className: "row_selected",
  },
  {
    number: "10",
    name: "Aditya Birla Group",
    symbol: "ADBRGRP",
    market: "BSE",
    className: "row_selected",
  },
  {
    number: "10",
    name: "Aditya Birla Group",
    symbol: "ADBRGRP",
    market: "BSE",
    className: "row_selected",
  },
  {
    number: "10",
    name: "Aditya Birla Group",
    symbol: "ADBRGRP",
    market: "BSE",
    className: "row_selected",
  },
  {
    number: "10",
    name: "Aditya Birla Group",
    symbol: "ADBRGRP",
    market: "BSE",
    className: "row_selected",
  },
  {
    number: "10",
    name: "Tata services",
    symbol: "TCS",
    market: "BSE",
    className: "row_selected",
  },
  {
    number: "10",
    name: "Aditya Birla Group",
    symbol: "ADBRGRP",
    market: "BSE",
    className: "row_selected",
  },
  {
    number: "10",
    name: "Aditya Birla Group",
    symbol: "ADBRGRP",
    market: "BSE",
    className: "row_selected",
  },
  {
    number: 11,
    name: "Aditya Birla Group",
    symbol: "ADBRGRP",
    market: "BSE",
  },
  {
    number: 12,
    name: "Aditya Birla Group",
    symbol: "ADBRGRP",
    market: "BSE",
  },
  {
    number: 13,
    name: "Aditya Birla Group",
    symbol: "ADBRGRP",
    market: "BSE",
  },
  {
    number: 14,
    name: "Aditya Birla Group",
    symbol: "ADBRGRP",
    market: "BSE",
  },
  {
    number: 15,
    name: "Aditya Birla Group",
    symbol: "ADBRGRP",
    market: "BSE",
  },
  {
    number: 16,
    name: "Aditya Birla Group",
    symbol: "ADBRGRP",
    market: "BSE",
  },
  {
    number: 17,
    name: "Aditya Birla Group",
    symbol: "ADBRGRP",
    market: "BSE",
  },
  {
    number: 18,
    name: "Aditya Birla Group",
    symbol: "ADBRGRP",
    market: "BSE",
  },
  {
    number: 19,
    name: "Aditya Birla Group",
    symbol: "ADBRGRP",
    market: "BSE",
  },
  {
    number: 20,
    name: "Aditya Birla Group",
    symbol: "ADBRGRP",
    market: "BSE",
  },
  {
    number: 21,
    name: "Relience Industries",
    symbol: "RLSINDS",
    market: "NSE",
  },
  {
    number: 22,
    name: "Tata Motors",
    symbol: "TATANTRS",
    market: "BSE",
  },
  {
    number: 23,
    name: "Aditya Birla Group",
    symbol: "ADBRGRP",
    market: "BSE",
  },
  {
    number: 24,
    name: "Aditya Birla Group",
    symbol: "ADBRGRP",
    market: "BSE",
  },
  {
    number: 25,
    name: "Aditya Birla Group",
    symbol: "ADBRGRP",
    market: "BSE",
  },
  {
    number: 26,
    name: "Aditya Birla Group",
    symbol: "ADBRGRP",
    market: "BSE",
  },
  {
    number: 27,
    name: "Aditya Birla Group",
    symbol: "ADBRGRP",
    market: "BSE",
  },
  {
    number: 28,
    name: "Aditya Birla Group",
    symbol: "ADBRGRP",
    market: "BSE",
  },
  {
    number: 29,
    name: "Aditya Birla Group",
    symbol: "ADBRGRP",
    market: "BSE",
  },
  {
    number: 30,
    name: "Aditya Birla Group",
    symbol: "ADBRGRP",
    market: "BSE",
  },
  {
    number: 31,
    name: "Aditya Birla Group",
    symbol: "ADBRGRP",
    market: "BSE",
  },
  {
    number: 32,
    name: "Aditya Birla Group",
    symbol: "ADBRGRP",
    market: "BSE",
  },
  {
    number: 33,
    name: "Aditya Birla Group",
    symbol: "ADBRGRP",
    market: "BSE",
  },
  {
    number: 34,
    name: "Aditya Birla Group",
    symbol: "ADBRGRP",
    market: "BSE",
  },
  {
    number: 35,
    name: "Aditya Birla Group",
    symbol: "ADBRGRP",
    market: "BSE",
  },
  {
    number: 36,
    name: "Aditya Birla Group",
    symbol: "ADBRGRP",
    market: "BSE",
  },
  {
    number: 37,
    name: "Aditya Birla Group",
    symbol: "ADBRGRP",
    market: "BSE",
  },
  {
    number: 38,
    name: "Aditya Birla Group",
    symbol: "ADBRGRP",
    market: "BSE",
  },
  {
    number: 39,
    name: "Aditya Birla Group",
    symbol: "ADBRGRP",
    market: "BSE",
  },
  {
    number: 40,
    name: "Aditya Birla Group",
    symbol: "ADBRGRP",
    market: "BSE",
  },
  {
    number: 41,
    name: "Relience Industries",
    symbol: "RLSINDS",
    market: "NSE",
  },
  {
    number: 42,
    name: "Tata Motors",
    symbol: "TATANTRS",
    market: "BSE",
  },
  {
    number: 43,
    name: "Aditya Birla Group",
    symbol: "ADBRGRP",
    market: "BSE",
  },
  {
    number: 44,
    name: "Aditya Birla Group",
    symbol: "ADBRGRP",
    market: "BSE",
  },
  {
    number: 45,
    name: "Aditya Birla Group",
    symbol: "ADBRGRP",
    market: "BSE",
  },
  {
    number: 46,
    name: "Aditya Birla Group",
    symbol: "ADBRGRP",
    market: "BSE",
  },
  {
    number: 47,
    name: "Aditya Birla Group",
    symbol: "ADBRGRP",
    market: "BSE",
  },
  {
    number: 48,
    name: "Aditya Birla Group",
    symbol: "ADBRGRP",
    market: "BSE",
  },
  {
    number: 49,
    name: "Aditya Birla Group",
    symbol: "ADBRGRP",
    market: "BSE",
  },
  {
    number: 50,
    name: "Aditya Birla Group",
    symbol: "ADBRGRP",
    market: "BSE",
  },
  {
    number: 51,
    name: "Aditya Birla Group",
    symbol: "ADBRGRP",
    market: "BSE",
  },
  {
    number: 52,
    name: "Aditya Birla Group",
    symbol: "ADBRGRP",
    market: "BSE",
  },
  {
    number: 53,
    name: "Aditya Birla Group",
    symbol: "ADBRGRP",
    market: "BSE",
  },
  {
    number: 54,
    name: "Aditya Birla Group",
    symbol: "ADBRGRP",
    market: "BSE",
  },
  {
    number: 55,
    name: "Aditya Birla Group",
    symbol: "ADBRGRP",
    market: "BSE",
  },
  {
    number: 56,
    name: "Aditya Birla Group",
    symbol: "ADBRGRP",
    market: "BSE",
  },
  {
    number: 57,
    name: "Aditya Birla Group",
    symbol: "ADBRGRP",
    market: "BSE",
  },
  {
    number: 58,
    name: "Aditya Birla Group",
    symbol: "ADBRGRP",
    market: "BSE",
  },
  {
    number: 59,
    name: "Aditya Birla Group",
    symbol: "ADBRGRP",
    market: "BSE",
  },
  {
    number: 60,
    name: "Aditya Birla Group",
    symbol: "ADBRGRP",
    market: "BSE",
  },
  {
    number: 61,
    name: "Relience Industries",
    symbol: "RLSINDS",
    market: "NSE",
  },
  {
    number: 62,
    name: "Tata Motors",
    symbol: "TATANTRS",
    market: "BSE",
  },
  {
    number: 63,
    name: "Aditya Birla Group",
    symbol: "ADBRGRP",
    market: "BSE",
  },
  {
    number: 64,
    name: "Aditya Birla Group",
    symbol: "ADBRGRP",
    market: "BSE",
  },
  {
    number: 65,
    name: "Aditya Birla Group",
    symbol: "ADBRGRP",
    market: "BSE",
  },
  {
    number: 66,
    name: "Aditya Birla Group",
    symbol: "ADBRGRP",
    market: "BSE",
  },
  {
    number: 67,
    name: "Aditya Birla Group",
    symbol: "ADBRGRP",
    market: "BSE",
  },
  {
    number: 68,
    name: "Aditya Birla Group",
    symbol: "ADBRGRP",
    market: "BSE",
  },
  {
    number: 69,
    name: "Aditya Birla Group",
    symbol: "ADBRGRP",
    market: "BSE",
  },
  {
    number: 70,
    name: "Aditya Birla Group",
    symbol: "ADBRGRP",
    market: "BSE",
  },
  {
    number: 71,
    name: "Aditya Birla Group",
    symbol: "ADBRGRP",
    market: "BSE",
  },
  {
    number: 72,
    name: "Aditya Birla Group",
    symbol: "ADBRGRP",
    market: "BSE",
  },
  {
    number: 73,
    name: "Aditya Birla Group",
    symbol: "ADBRGRP",
    market: "BSE",
  },
  {
    number: 74,
    name: "Aditya Birla Group",
    symbol: "ADBRGRP",
    market: "BSE",
  },
  {
    number: 75,
    name: "Aditya Birla Group",
    symbol: "ADBRGRP",
    market: "BSE",
  },
  {
    number: 76,
    name: "Aditya Birla Group",
    symbol: "ADBRGRP",
    market: "BSE",
  },
  {
    number: 77,
    name: "Aditya Birla Group",
    symbol: "ADBRGRP",
    market: "BSE",
  },
  {
    number: 78,
    name: "Aditya Birla Group",
    symbol: "ADBRGRP",
    market: "BSE",
  },
  {
    number: 79,
    name: "Aditya Birla Group",
    symbol: "ADBRGRP",
    market: "BSE",
  },
  {
    number: 80,
    name: "Aditya Birla Group",
    symbol: "ADBRGRP",
    market: "BSE",
  },
  {
    number: 81,
    name: "Relience Industries",
    symbol: "RLSINDS",
    market: "NSE",
  },
  {
    number: 82,
    name: "Tata Motors",
    symbol: "TATANTRS",
    market: "BSE",
  },
  {
    number: 83,
    name: "Aditya Birla Group",
    symbol: "ADBRGRP",
    market: "BSE",
  },
  {
    number: 84,
    name: "Aditya Birla Group",
    symbol: "ADBRGRP",
    market: "BSE",
  },
  {
    number: 85,
    name: "Aditya Birla Group",
    symbol: "ADBRGRP",
    market: "BSE",
  },
  {
    number: 86,
    name: "Aditya Birla Group",
    symbol: "ADBRGRP",
    market: "BSE",
  },
  {
    number: 87,
    name: "Aditya Birla Group",
    symbol: "ADBRGRP",
    market: "BSE",
  },
  {
    number: 88,
    name: "Aditya Birla Group",
    symbol: "ADBRGRP",
    market: "BSE",
  },
  {
    number: 89,
    name: "Aditya Birla Group",
    symbol: "ADBRGRP",
    market: "BSE",
  },
  {
    number: 90,
    name: "Aditya Birla Group",
    symbol: "ADBRGRP",
    market: "BSE",
  },
  {
    number: 91,
    name: "Aditya Birla Group",
    symbol: "ADBRGRP",
    market: "BSE",
  },
  {
    number: 92,
    name: "Aditya Birla Group",
    symbol: "ADBRGRP",
    market: "BSE",
  },
  {
    number: 93,
    name: "Aditya Birla Group",
    symbol: "ADBRGRP",
    market: "BSE",
  },
  {
    number: 94,
    name: "Aditya Birla Group",
    symbol: "ADBRGRP",
    market: "BSE",
  },
  {
    number: 95,
    name: "Aditya Birla Group",
    symbol: "ADBRGRP",
    market: "BSE",
  },
  {
    number: 96,
    name: "Aditya Birla Group",
    symbol: "ADBRGRP",
    market: "BSE",
  },
  {
    number: 97,
    name: "Aditya Birla Group",
    symbol: "ADBRGRP",
    market: "BSE",
  },
  {
    number: 98,
    name: "Aditya Birla Group",
    symbol: "ADBRGRP",
    market: "BSE",
  },
  {
    number: 99,
    name: "Aditya Birla Group",
    symbol: "ADBRGRP",
    market: "BSE",
  },
  {
    number: 100,
    name: "Aditya Birla Group",
    symbol: "ADBRGRP",
    market: "BSE",
  },
  {
    number: 101,
    name: "Jio",
    symbol: "JIOSM",
    market: "SME",
  },
];
